var searchData=
[
  ['callback_0',['Global Interrupt Callback',['../md_docs_2examples.html#autotoc_md58',1,'']]],
  ['callbacks_1',['Per-Pin Interrupt Callbacks',['../md_docs_2configuration.html#autotoc_md46',1,'']]],
  ['can_20i_20use_20multiple_20pcal9555a_20devices_2',['Q: Can I use multiple PCAL9555A devices?',['../md_docs_2troubleshooting.html#autotoc_md134',1,'']]],
  ['changes_3',['Dynamic Address Changes',['../md_docs_2configuration.html#autotoc_md32',1,'']]],
  ['check_20for_20errors_4',['Q: How do I check for errors?',['../md_docs_2troubleshooting.html#autotoc_md137',1,'']]],
  ['class_5',['Class',['../md_docs_2api__reference.html#autotoc_md13',1,'Core Class'],['../md_docs_2platform__integration.html#autotoc_md101',1,'Step 1: Create Your Implementation Class']]],
  ['code_6',['Source Code',['../md_docs_2api__reference.html#autotoc_md12',1,'']]],
  ['common_20error_20messages_7',['Common Error Messages',['../md_docs_2troubleshooting.html#autotoc_md126',1,'']]],
  ['common_20pitfalls_8',['Common Pitfalls',['../md_docs_2platform__integration.html#autotoc_md106',1,'']]],
  ['communication_20failures_9',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md128',1,'']]],
  ['comparison_10',['Performance Comparison',['../md_docs_2platform__integration.html#autotoc_md98',1,'']]],
  ['compile_20time_20polymorphism_20strong_11',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md94',1,'']]],
  ['configuration_12',['Configuration',['../md_docs_2hardware__setup.html#autotoc_md67',1,'Address Configuration'],['../md_docs_2configuration.html',1,'Configuration'],['../md_docs_2configuration.html#autotoc_md42',1,'Default Configuration'],['../md_docs_2configuration.html#autotoc_md30',1,'I2C Address Configuration'],['../md_docs_2hardware__setup.html#autotoc_md68',1,'I2C Bus Configuration'],['../md_docs_2hardware__setup.html#autotoc_md66',1,'I2C Configuration'],['../md_docs_2configuration.html#autotoc_md44',1,'Interrupt Configuration'],['../md_docs_2configuration.html#autotoc_md36',1,'Runtime Configuration']]],
  ['configuration_20optional_13',['Kconfig Configuration (Optional)',['../md_docs_2configuration.html#autotoc_md33',1,'']]],
  ['configuration_20options_14',['Configuration Options',['../md_docs_2configuration.html#autotoc_md34',1,'']]],
  ['configuration_20table_15',['Address Pin Configuration Table',['../md_docs_2configuration.html#autotoc_md31',1,'']]],
  ['configure_20and_20use_20pins_16',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md121',1,'']]],
  ['configure_20multiple_20interrupts_17',['Configure Multiple Interrupts',['../md_docs_2examples.html#autotoc_md57',1,'']]],
  ['connections_18',['Connections',['../md_docs_2hardware__setup.html#autotoc_md62',1,'Basic I2C Connections'],['../md_docs_2hardware__setup.html#autotoc_md61',1,'Pin Connections']]],
  ['contents_19',['📚 Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['contributing_20',['🤝 Contributing',['../index.html#autotoc_md9',1,'']]],
  ['control_21',['Example 1: Basic GPIO Control',['../md_docs_2examples.html#autotoc_md54',1,'']]],
  ['copy_20files_22',['Option 1: Copy Files',['../md_docs_2installation.html#autotoc_md86',1,'']]],
  ['core_20class_23',['Core Class',['../md_docs_2api__reference.html#autotoc_md13',1,'']]],
  ['correct_20crtp_20implementation_24',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['correct_20template_20parameter_25',['✅ Correct Template Parameter',['../md_docs_2platform__integration.html#autotoc_md110',1,'']]],
  ['create_20driver_20instance_26',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md119',1,'']]],
  ['create_20your_20implementation_20class_27',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md101',1,'']]],
  ['crtp_20curiously_20recurring_20template_20pattern_28',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md91',1,'']]],
  ['crtp_20implementation_29',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['crtp_20instead_20of_20virtual_20functions_30',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md92',1,'']]],
  ['crtp_20works_31',['How CRTP Works',['../md_docs_2platform__integration.html#autotoc_md97',1,'']]],
  ['curiously_20recurring_20template_20pattern_32',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md91',1,'']]]
];
