var searchData=
[
  ['i_20o_0',['Pin I/O',['../md_docs_2api__reference.html#autotoc_md25',1,'']]],
  ['i2c_20address_20configuration_1',['I2C Address Configuration',['../md_docs_2configuration.html#autotoc_md38',1,'']]],
  ['i2c_20bus_20configuration_2',['I2C Bus Configuration',['../md_docs_2hardware__setup.html#autotoc_md82',1,'']]],
  ['i2c_20communication_20failures_3',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md142',1,'']]],
  ['i2c_20configuration_4',['I2C Configuration',['../md_docs_2hardware__setup.html#autotoc_md80',1,'']]],
  ['i2c_20connections_5',['Basic I2C Connections',['../md_docs_2hardware__setup.html#autotoc_md76',1,'']]],
  ['i2c_20interface_6',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['i2c_20interface_20for_20your_20platform_7',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['i2c_20nacks_20on_20registers_200x40_200x4f_20during_20init_8',['Error: I2C NACKs on Registers 0x40-0x4F During Init',['../md_docs_2troubleshooting.html#autotoc_md146',1,'']]],
  ['i2ctype_20tt_9',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md21',1,'']]],
  ['idf_10',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md117',1,'']]],
  ['implement_20the_20i2c_20interface_11',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['implement_20the_20i2c_20interface_20for_20your_20platform_12',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['implementation_13',['Implementation',['../md_docs_2platform__integration.html#autotoc_md122',1,'✅ Correct CRTP Implementation'],['../md_docs_2platform__integration.html#autotoc_md125',1,'Testing Your Implementation']]],
  ['implementation_20class_14',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md115',1,'']]],
  ['implementation_20steps_15',['Implementation Steps',['../md_docs_2platform__integration.html#autotoc_md114',1,'']]],
  ['include_20the_20header_16',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md131',1,'']]],
  ['including_20the_20header_17',['Including the Header',['../md_docs_2installation.html#autotoc_md102',1,'']]],
  ['incorrect_20pin_20states_18',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['init_19',['Error: I2C NACKs on Registers 0x40-0x4F During Init',['../md_docs_2troubleshooting.html#autotoc_md146',1,'']]],
  ['initialization_20',['Initialization',['../md_docs_2api__reference.html#autotoc_md23',1,'']]],
  ['initialize_21',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md134',1,'']]],
  ['input_20latch_20pcal9555a_20only_22',['Input Latch (PCAL9555A only)',['../md_docs_2api__reference.html#autotoc_md31',1,'']]],
  ['input_20pins_23',['For Input Pins',['../md_docs_2configuration.html#autotoc_md58',1,'']]],
  ['inputs_24',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md60',1,'']]],
  ['installation_25',['Installation',['../md_docs_2installation.html',1,'']]],
  ['instance_26',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md133',1,'']]],
  ['instead_20of_20virtual_20functions_27',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md106',1,'']]],
  ['integration_28',['Integration',['../md_docs_2installation.html#autotoc_md99',1,'']]],
  ['integration_20guide_29',['Platform Integration Guide',['../md_docs_2platform__integration.html',1,'']]],
  ['integration_20strong_30',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md93',1,'']]],
  ['interactive_20test_20wiring_31',['Interactive test wiring',['../index.html#autotoc_md16',1,'']]],
  ['interface_32',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['interface_20definition_33',['Interface Definition',['../md_docs_2platform__integration.html#autotoc_md113',1,'']]],
  ['interface_20for_20your_20platform_34',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['interrupt_20callback_35',['Global Interrupt Callback',['../md_docs_2examples.html#autotoc_md67',1,'']]],
  ['interrupt_20callbacks_36',['Per-Pin Interrupt Callbacks',['../md_docs_2configuration.html#autotoc_md55',1,'']]],
  ['interrupt_20configuration_37',['Interrupt Configuration',['../md_docs_2configuration.html#autotoc_md53',1,'']]],
  ['interrupt_20driven_20inputs_38',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md60',1,'']]],
  ['interrupt_20handling_39',['Example 3: Interrupt Handling',['../md_docs_2examples.html#autotoc_md65',1,'']]],
  ['interrupt_20pin_20optional_40',['Interrupt Pin (Optional)',['../md_docs_2hardware__setup.html#autotoc_md87',1,'']]],
  ['interrupt_20setup_41',['Basic Interrupt Setup',['../md_docs_2configuration.html#autotoc_md54',1,'']]],
  ['interrupt_20status_42',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md56',1,'']]],
  ['interrupts_43',['Interrupts',['../md_docs_2examples.html#autotoc_md66',1,'Configure Multiple Interrupts'],['../md_docs_2api__reference.html#autotoc_md28',1,'Interrupts']]],
  ['inversion_44',['Polarity Inversion',['../md_docs_2configuration.html#autotoc_md49',1,'']]],
  ['it_45',['2. Create the driver and use it',['../index.html#autotoc_md5',1,'']]]
];
