var searchData=
[
  ['callback_0',['Global Interrupt Callback',['../md_docs_2examples.html#autotoc_md74',1,'']]],
  ['callbacks_1',['Per-Pin Interrupt Callbacks',['../md_docs_2configuration.html#autotoc_md62',1,'']]],
  ['can_20i_20use_20multiple_20devices_2',['Q: Can I use multiple devices?',['../md_docs_2troubleshooting.html#autotoc_md157',1,'']]],
  ['changes_3',['Dynamic Address Changes',['../md_docs_2configuration.html#autotoc_md47',1,'']]],
  ['check_20for_20errors_4',['Q: How do I check for errors?',['../md_docs_2troubleshooting.html#autotoc_md161',1,'']]],
  ['chip_20i_20have_20pca9555_20vs_20pcal9555a_5',['Q: How do I know which chip I have (PCA9555 vs PCAL9555A)?',['../md_docs_2troubleshooting.html#autotoc_md158',1,'']]],
  ['chip_20variant_20configuration_6',['Chip Variant Configuration',['../md_docs_2configuration.html#autotoc_md59',1,'']]],
  ['chip_20variant_20detection_7',['Chip Variant Detection',['../md_docs_2api__reference.html#autotoc_md34',1,'Chip Variant Detection'],['../md_docs_2examples.html#autotoc_md76',1,'Example 8: Chip Variant Detection']]],
  ['chipvariant_20shows_20unknown_8',['Error: ChipVariant Shows &quot;Unknown&quot;',['../md_docs_2troubleshooting.html#autotoc_md153',1,'']]],
  ['class_9',['Class',['../md_docs_2api__reference.html#autotoc_md20',1,'Core Class'],['../md_docs_2platform__integration.html#autotoc_md122',1,'Step 1: Create Your Implementation Class']]],
  ['cmake_20integration_20guide_10',['PCAL95555 — CMake Integration Guide',['../md_docs_2cmake__integration.html',1,'']]],
  ['code_11',['Source Code',['../md_docs_2api__reference.html#autotoc_md19',1,'']]],
  ['common_20error_20messages_12',['Common Error Messages',['../md_docs_2troubleshooting.html#autotoc_md147',1,'']]],
  ['common_20pitfalls_13',['Common Pitfalls',['../md_docs_2platform__integration.html#autotoc_md127',1,'']]],
  ['communication_20failures_14',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md149',1,'']]],
  ['comparison_15',['Performance Comparison',['../md_docs_2platform__integration.html#autotoc_md119',1,'']]],
  ['compile_20time_20polymorphism_20strong_16',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md115',1,'']]],
  ['component_17',['Component',['../md_docs_2cmake__integration.html#autotoc_md39',1,'1. Reference the Component'],['../md_docs_2cmake__integration.html#autotoc_md41',1,'3. Require the Component']]],
  ['comprehensive_20test_20suite_20tt_20pcal95555_5fcomprehensive_5ftest_20tt_18',['Comprehensive Test Suite (&lt;tt&gt;pcal95555_comprehensive_test&lt;/tt&gt;)',['../index.html#autotoc_md11',1,'']]],
  ['configuration_19',['Configuration',['../md_docs_2hardware__setup.html#autotoc_md88',1,'Address Configuration'],['../md_docs_2configuration.html#autotoc_md59',1,'Chip Variant Configuration'],['../md_docs_2configuration.html',1,'Configuration'],['../md_docs_2configuration.html#autotoc_md57',1,'Default Configuration'],['../md_docs_2configuration.html#autotoc_md45',1,'I2C Address Configuration'],['../md_docs_2hardware__setup.html#autotoc_md89',1,'I2C Bus Configuration'],['../md_docs_2hardware__setup.html#autotoc_md87',1,'I2C Configuration'],['../md_docs_2configuration.html#autotoc_md60',1,'Interrupt Configuration'],['../md_docs_2configuration.html#autotoc_md51',1,'Runtime Configuration']]],
  ['configuration_20optional_20',['Kconfig Configuration (Optional)',['../md_docs_2configuration.html#autotoc_md48',1,'']]],
  ['configuration_20options_21',['Configuration Options',['../md_docs_2configuration.html#autotoc_md49',1,'']]],
  ['configuration_20table_22',['Address Pin Configuration Table',['../md_docs_2configuration.html#autotoc_md46',1,'']]],
  ['configure_20and_20use_20pins_23',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md142',1,'']]],
  ['configure_20multiple_20interrupts_24',['Configure Multiple Interrupts',['../md_docs_2examples.html#autotoc_md73',1,'']]],
  ['connections_25',['Connections',['../md_docs_2hardware__setup.html#autotoc_md83',1,'Basic I2C Connections'],['../md_docs_2hardware__setup.html#autotoc_md82',1,'Pin Connections']]],
  ['contributing_26',['Contributing',['../index.html#autotoc_md17',1,'']]],
  ['control_27',['Example 1: Basic GPIO Control',['../md_docs_2examples.html#autotoc_md70',1,'']]],
  ['copy_20files_28',['Option 1: Copy Files',['../md_docs_2installation.html#autotoc_md107',1,'']]],
  ['core_20class_29',['Core Class',['../md_docs_2api__reference.html#autotoc_md20',1,'']]],
  ['correct_20crtp_20implementation_30',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md129',1,'']]],
  ['correct_20template_20parameter_31',['✅ Correct Template Parameter',['../md_docs_2platform__integration.html#autotoc_md131',1,'']]],
  ['create_20driver_20instance_32',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md140',1,'']]],
  ['create_20the_20driver_20and_20use_20it_33',['2. Create the driver and use it',['../index.html#autotoc_md5',1,'']]],
  ['create_20your_20implementation_20class_34',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md122',1,'']]],
  ['crtp_20curiously_20recurring_20template_20pattern_35',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md112',1,'']]],
  ['crtp_20implementation_36',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md129',1,'']]],
  ['crtp_20instead_20of_20virtual_20functions_37',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md113',1,'']]],
  ['crtp_20works_38',['How CRTP Works',['../md_docs_2platform__integration.html#autotoc_md118',1,'']]],
  ['curiously_20recurring_20template_20pattern_39',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md112',1,'']]]
];
