var searchData=
[
  ['parameter_0',['Parameter',['../md_docs_2platform__integration.html#autotoc_md104',1,'✅ Correct Template Parameter'],['../md_docs_2platform__integration.html#autotoc_md103',1,'❌ Don&apos;t Forget the Template Parameter']]],
  ['pattern_1',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md85',1,'']]],
  ['pcal95555_20documentation_2',['HF-PCAL95555 Documentation',['../md_docs_2index.html',1,'']]],
  ['pcal95555_20driver_3',['HF-PCAL95555 Driver',['../index.html',1,'']]],
  ['pcal95555_20i2ctype_20tt_4',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md14',1,'']]],
  ['pcal9555a_5',['Single PCAL9555A',['../md_docs_2hardware__setup.html#autotoc_md65',1,'']]],
  ['pcal9555a_20devices_6',['Multiple PCAL9555A Devices',['../md_docs_2hardware__setup.html#autotoc_md66',1,'']]],
  ['pcal9555a_20devices_7',['Q: Can I use multiple PCAL9555A devices?',['../md_docs_2troubleshooting.html#autotoc_md128',1,'']]],
  ['performance_20comparison_8',['Performance Comparison',['../md_docs_2platform__integration.html#autotoc_md92',1,'']]],
  ['physical_20layout_20recommendations_9',['Physical Layout Recommendations',['../md_docs_2hardware__setup.html#autotoc_md63',1,'']]],
  ['pin_20connections_10',['Pin Connections',['../md_docs_2hardware__setup.html#autotoc_md55',1,'']]],
  ['pin_20descriptions_11',['Pin Descriptions',['../md_docs_2hardware__setup.html#autotoc_md57',1,'']]],
  ['pin_20direction_12',['Pin Direction',['../md_docs_2api__reference.html#autotoc_md17',1,'Pin Direction'],['../md_docs_2configuration.html#autotoc_md34',1,'Pin Direction']]],
  ['pin_20i_20o_13',['Pin I/O',['../md_docs_2api__reference.html#autotoc_md18',1,'']]],
  ['pin_20optional_14',['Pin Optional',['../md_docs_2hardware__setup.html#autotoc_md67',1,'Interrupt Pin (Optional)'],['../md_docs_2hardware__setup.html#autotoc_md68',1,'Reset Pin (Optional)']]],
  ['pin_20states_15',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md123',1,'']]],
  ['pin_20writes_20not_20work_16',['Q: Why do my pin writes not work?',['../md_docs_2troubleshooting.html#autotoc_md126',1,'']]],
  ['pins_17',['Pins',['../md_docs_2configuration.html#autotoc_md45',1,'For Input Pins'],['../md_docs_2configuration.html#autotoc_md46',1,'For Output Pins'],['../md_docs_2hardware__setup.html#autotoc_md58',1,'GPIO Pins'],['../md_docs_2quickstart.html#autotoc_md115',1,'Step 5: Configure and Use Pins']]],
  ['pitfalls_18',['Common Pitfalls',['../md_docs_2platform__integration.html#autotoc_md100',1,'']]],
  ['platform_20integration_20guide_19',['Platform Integration Guide',['../md_docs_2platform__integration.html',1,'']]],
  ['platform_20specific_20examples_20',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md96',1,'']]],
  ['polarity_21',['Polarity',['../md_docs_2api__reference.html#autotoc_md23',1,'']]],
  ['polarity_20inversion_22',['Polarity Inversion',['../md_docs_2configuration.html#autotoc_md38',1,'']]],
  ['polymorphism_20strong_23',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md88',1,'']]],
  ['power_20requirements_24',['Power Requirements',['../md_docs_2hardware__setup.html#autotoc_md59',1,'']]],
  ['prerequisites_25',['Prerequisites',['../md_docs_2installation.html#autotoc_md78',1,'Prerequisites'],['../md_docs_2quickstart.html#autotoc_md108',1,'Prerequisites']]],
  ['pull_20resistors_26',['Pull Resistors',['../md_docs_2configuration.html#autotoc_md35',1,'']]],
  ['pull_20up_20and_20pull_20down_27',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md129',1,'']]],
  ['pull_20up_20pull_20down_28',['Pull-up/Pull-down',['../md_docs_2api__reference.html#autotoc_md19',1,'']]]
];
