var searchData=
[
  ['callback_0',['Global Interrupt Callback',['../md_docs_2examples.html#autotoc_md67',1,'']]],
  ['callbacks_1',['Per-Pin Interrupt Callbacks',['../md_docs_2configuration.html#autotoc_md55',1,'']]],
  ['can_20i_20use_20multiple_20devices_2',['Q: Can I use multiple devices?',['../md_docs_2troubleshooting.html#autotoc_md150',1,'']]],
  ['changes_3',['Dynamic Address Changes',['../md_docs_2configuration.html#autotoc_md40',1,'']]],
  ['check_20for_20errors_4',['Q: How do I check for errors?',['../md_docs_2troubleshooting.html#autotoc_md154',1,'']]],
  ['chip_20i_20have_20pca9555_20vs_20pcal9555a_5',['Q: How do I know which chip I have (PCA9555 vs PCAL9555A)?',['../md_docs_2troubleshooting.html#autotoc_md151',1,'']]],
  ['chip_20variant_20configuration_6',['Chip Variant Configuration',['../md_docs_2configuration.html#autotoc_md52',1,'']]],
  ['chip_20variant_20detection_7',['Chip Variant Detection',['../md_docs_2api__reference.html#autotoc_md34',1,'Chip Variant Detection'],['../md_docs_2examples.html#autotoc_md69',1,'Example 8: Chip Variant Detection']]],
  ['chipvariant_20shows_20unknown_8',['Error: ChipVariant Shows &quot;Unknown&quot;',['../md_docs_2troubleshooting.html#autotoc_md146',1,'']]],
  ['class_9',['Class',['../md_docs_2api__reference.html#autotoc_md20',1,'Core Class'],['../md_docs_2platform__integration.html#autotoc_md115',1,'Step 1: Create Your Implementation Class']]],
  ['code_10',['Source Code',['../md_docs_2api__reference.html#autotoc_md19',1,'']]],
  ['common_20error_20messages_11',['Common Error Messages',['../md_docs_2troubleshooting.html#autotoc_md140',1,'']]],
  ['common_20pitfalls_12',['Common Pitfalls',['../md_docs_2platform__integration.html#autotoc_md120',1,'']]],
  ['communication_20failures_13',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md142',1,'']]],
  ['comparison_14',['Performance Comparison',['../md_docs_2platform__integration.html#autotoc_md112',1,'']]],
  ['compile_20time_20polymorphism_20strong_15',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['comprehensive_20test_20suite_20tt_20pcal95555_5fcomprehensive_5ftest_20tt_16',['Comprehensive Test Suite (&lt;tt&gt;pcal95555_comprehensive_test&lt;/tt&gt;)',['../index.html#autotoc_md11',1,'']]],
  ['configuration_17',['Configuration',['../md_docs_2hardware__setup.html#autotoc_md81',1,'Address Configuration'],['../md_docs_2configuration.html#autotoc_md52',1,'Chip Variant Configuration'],['../md_docs_2configuration.html',1,'Configuration'],['../md_docs_2configuration.html#autotoc_md50',1,'Default Configuration'],['../md_docs_2configuration.html#autotoc_md38',1,'I2C Address Configuration'],['../md_docs_2hardware__setup.html#autotoc_md82',1,'I2C Bus Configuration'],['../md_docs_2hardware__setup.html#autotoc_md80',1,'I2C Configuration'],['../md_docs_2configuration.html#autotoc_md53',1,'Interrupt Configuration'],['../md_docs_2configuration.html#autotoc_md44',1,'Runtime Configuration']]],
  ['configuration_20optional_18',['Kconfig Configuration (Optional)',['../md_docs_2configuration.html#autotoc_md41',1,'']]],
  ['configuration_20options_19',['Configuration Options',['../md_docs_2configuration.html#autotoc_md42',1,'']]],
  ['configuration_20table_20',['Address Pin Configuration Table',['../md_docs_2configuration.html#autotoc_md39',1,'']]],
  ['configure_20and_20use_20pins_21',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md135',1,'']]],
  ['configure_20multiple_20interrupts_22',['Configure Multiple Interrupts',['../md_docs_2examples.html#autotoc_md66',1,'']]],
  ['connections_23',['Connections',['../md_docs_2hardware__setup.html#autotoc_md76',1,'Basic I2C Connections'],['../md_docs_2hardware__setup.html#autotoc_md75',1,'Pin Connections']]],
  ['contributing_24',['Contributing',['../index.html#autotoc_md17',1,'']]],
  ['control_25',['Example 1: Basic GPIO Control',['../md_docs_2examples.html#autotoc_md63',1,'']]],
  ['copy_20files_26',['Option 1: Copy Files',['../md_docs_2installation.html#autotoc_md100',1,'']]],
  ['core_20class_27',['Core Class',['../md_docs_2api__reference.html#autotoc_md20',1,'']]],
  ['correct_20crtp_20implementation_28',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md122',1,'']]],
  ['correct_20template_20parameter_29',['✅ Correct Template Parameter',['../md_docs_2platform__integration.html#autotoc_md124',1,'']]],
  ['create_20driver_20instance_30',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md133',1,'']]],
  ['create_20the_20driver_20and_20use_20it_31',['2. Create the driver and use it',['../index.html#autotoc_md5',1,'']]],
  ['create_20your_20implementation_20class_32',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md115',1,'']]],
  ['crtp_20curiously_20recurring_20template_20pattern_33',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md105',1,'']]],
  ['crtp_20implementation_34',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md122',1,'']]],
  ['crtp_20instead_20of_20virtual_20functions_35',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md106',1,'']]],
  ['crtp_20works_36',['How CRTP Works',['../md_docs_2platform__integration.html#autotoc_md111',1,'']]],
  ['curiously_20recurring_20template_20pattern_37',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md105',1,'']]]
];
