var searchData=
[
  ['i_20o_0',['Pin I/O',['../md_docs_2api__reference.html#autotoc_md20',1,'']]],
  ['i_20use_20interrupts_1',['Q: How do I use interrupts?',['../md_docs_2troubleshooting.html#autotoc_md130',1,'']]],
  ['i_20use_20multiple_20pcal9555a_20devices_2',['Q: Can I use multiple PCAL9555A devices?',['../md_docs_2troubleshooting.html#autotoc_md131',1,'']]],
  ['i2c_20address_20configuration_3',['I2C Address Configuration',['../md_docs_2configuration.html#autotoc_md32',1,'']]],
  ['i2c_20bus_20configuration_4',['I2C Bus Configuration',['../md_docs_2hardware__setup.html#autotoc_md65',1,'']]],
  ['i2c_20communication_20failures_5',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md125',1,'']]],
  ['i2c_20configuration_6',['I2C Configuration',['../md_docs_2hardware__setup.html#autotoc_md63',1,'']]],
  ['i2c_20connections_7',['Basic I2C Connections',['../md_docs_2hardware__setup.html#autotoc_md59',1,'']]],
  ['i2c_20interface_8',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md115',1,'']]],
  ['i2ctype_20tt_9',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md14',1,'']]],
  ['idf_10',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md100',1,'']]],
  ['implement_20the_20i2c_20interface_11',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md115',1,'']]],
  ['implementation_12',['Implementation',['../md_docs_2platform__integration.html#autotoc_md105',1,'✅ Correct CRTP Implementation'],['../md_docs_2platform__integration.html#autotoc_md108',1,'Testing Your Implementation']]],
  ['implementation_20class_13',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md98',1,'']]],
  ['implementation_20steps_14',['Implementation Steps',['../md_docs_2platform__integration.html#autotoc_md97',1,'']]],
  ['include_20the_20header_15',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md114',1,'']]],
  ['including_20the_20header_16',['Including the Header',['../md_docs_2installation.html#autotoc_md85',1,'']]],
  ['incorrect_20pin_20states_17',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md126',1,'']]],
  ['initialization_18',['Initialization',['../md_docs_2api__reference.html#autotoc_md16',1,'']]],
  ['initialize_19',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md117',1,'']]],
  ['input_20pins_20',['For Input Pins',['../md_docs_2configuration.html#autotoc_md48',1,'']]],
  ['inputs_21',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md50',1,'']]],
  ['installation_22',['Installation',['../index.html#autotoc_md5',1,'🔧 Installation'],['../md_docs_2installation.html',1,'Installation']]],
  ['instance_23',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md116',1,'']]],
  ['instead_20of_20virtual_20functions_24',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md89',1,'']]],
  ['integration_25',['Integration',['../md_docs_2installation.html#autotoc_md82',1,'']]],
  ['integration_20guide_26',['Platform Integration Guide',['../md_docs_2platform__integration.html',1,'']]],
  ['integration_20strong_27',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md76',1,'']]],
  ['interface_28',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md115',1,'']]],
  ['interface_20definition_29',['Interface Definition',['../md_docs_2platform__integration.html#autotoc_md96',1,'']]],
  ['interrupt_20configuration_30',['Interrupt Configuration',['../md_docs_2configuration.html#autotoc_md44',1,'']]],
  ['interrupt_20driven_20inputs_31',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md50',1,'']]],
  ['interrupt_20handling_32',['Example 3: Interrupt Handling',['../md_docs_2examples.html#autotoc_md55',1,'']]],
  ['interrupt_20pin_20optional_33',['Interrupt Pin (Optional)',['../md_docs_2hardware__setup.html#autotoc_md70',1,'']]],
  ['interrupt_20status_34',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md46',1,'']]],
  ['interrupts_35',['Interrupts',['../md_docs_2configuration.html#autotoc_md45',1,'Enable Interrupts'],['../md_docs_2api__reference.html#autotoc_md24',1,'Interrupts'],['../md_docs_2troubleshooting.html#autotoc_md130',1,'Q: How do I use interrupts?']]],
  ['inversion_36',['Polarity Inversion',['../md_docs_2configuration.html#autotoc_md41',1,'']]]
];
