var searchData=
[
  ['t_20forget_20the_20template_20parameter_0',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md106',1,'']]],
  ['t_20use_20virtual_20functions_1',['❌ Don&apos;t Use Virtual Functions',['../md_docs_2platform__integration.html#autotoc_md104',1,'']]],
  ['table_20of_20contents_2',['📚 Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['template_20parameter_3',['Template Parameter',['../md_docs_2platform__integration.html#autotoc_md107',1,'✅ Correct Template Parameter'],['../md_docs_2platform__integration.html#autotoc_md106',1,'❌ Don&apos;t Forget the Template Parameter']]],
  ['template_20pattern_4',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md88',1,'']]],
  ['testing_20your_20implementation_5',['Testing Your Implementation',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['the_20difference_20between_20pull_20up_20and_20pull_20down_6',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md132',1,'']]],
  ['the_20header_7',['The Header',['../md_docs_2installation.html#autotoc_md85',1,'Including the Header'],['../md_docs_2quickstart.html#autotoc_md114',1,'Step 1: Include the Header']]],
  ['the_20i2c_20interface_8',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md115',1,'']]],
  ['the_20template_20parameter_9',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md106',1,'']]],
  ['time_20polymorphism_20strong_10',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md91',1,'']]],
  ['togglepin_20pin_20tt_11',['&lt;tt&gt;TogglePin(pin)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md22',1,'']]],
  ['troubleshooting_12',['Troubleshooting',['../md_docs_2troubleshooting.html',1,'Troubleshooting'],['../md_docs_2quickstart.html#autotoc_md120',1,'Troubleshooting']]],
  ['troubleshooting_20strong_13',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md78',1,'']]],
  ['tt_20clearerrorflags_20mask_20tt_14',['&lt;tt&gt;ClearErrorFlags(mask)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md30',1,'']]],
  ['tt_20configureinterruptmask_20mask_20tt_15',['&lt;tt&gt;ConfigureInterruptMask(mask)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md25',1,'']]],
  ['tt_20enableinputlatch_20pin_20enable_20tt_16',['&lt;tt&gt;EnableInputLatch(pin, enable)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md29',1,'']]],
  ['tt_20pcal95555_20i2ctype_20tt_17',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md14',1,'']]],
  ['tt_20readpin_20pin_20tt_18',['&lt;tt&gt;ReadPin(pin)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md21',1,'']]],
  ['tt_20resettodefault_20tt_19',['&lt;tt&gt;ResetToDefault()&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md17',1,'']]],
  ['tt_20setinterruptcallback_20callback_20tt_20',['&lt;tt&gt;SetInterruptCallback(callback)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md26',1,'']]],
  ['tt_20setoutputmode_20port_5f0_5fod_20port_5f1_5fod_20tt_21',['&lt;tt&gt;SetOutputMode(port_0_od, port_1_od)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md28',1,'']]],
  ['tt_20setpindirection_20pin_20dir_20tt_22',['&lt;tt&gt;SetPinDirection(pin, dir)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md19',1,'']]],
  ['tt_20setpulldirection_20pin_20pull_5fup_20tt_23',['&lt;tt&gt;SetPullDirection(pin, pull_up)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md23',1,'']]],
  ['tt_20togglepin_20pin_20tt_24',['&lt;tt&gt;TogglePin(pin)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md22',1,'']]],
  ['type_20safety_25',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md93',1,'']]]
];
