var searchData=
[
  ['default_20configuration_0',['Default Configuration',['../md_docs_2configuration.html#autotoc_md42',1,'']]],
  ['definition_1',['Interface Definition',['../md_docs_2platform__integration.html#autotoc_md99',1,'']]],
  ['descriptions_2',['Pin Descriptions',['../md_docs_2hardware__setup.html#autotoc_md63',1,'']]],
  ['detected_3',['Error: Device Not Detected',['../md_docs_2troubleshooting.html#autotoc_md127',1,'']]],
  ['device_20not_20detected_4',['Error: Device Not Detected',['../md_docs_2troubleshooting.html#autotoc_md127',1,'']]],
  ['devices_5',['Devices',['../md_docs_2hardware__setup.html#autotoc_md72',1,'Multiple PCAL9555A Devices'],['../md_docs_2troubleshooting.html#autotoc_md134',1,'Q: Can I use multiple PCAL9555A devices?']]],
  ['diagram_6',['Example Wiring Diagram',['../md_docs_2hardware__setup.html#autotoc_md70',1,'']]],
  ['difference_20between_20pull_20up_20and_20pull_20down_7',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md135',1,'']]],
  ['direction_8',['Direction',['../md_docs_2api__reference.html#autotoc_md17',1,'Pin Direction'],['../md_docs_2configuration.html#autotoc_md37',1,'Pin Direction']]],
  ['do_20i_20check_20for_20errors_9',['Q: How do I check for errors?',['../md_docs_2troubleshooting.html#autotoc_md137',1,'']]],
  ['do_20i_20use_20interrupts_10',['Q: How do I use interrupts?',['../md_docs_2troubleshooting.html#autotoc_md133',1,'']]],
  ['do_20my_20pin_20writes_20not_20work_11',['Q: Why do my pin writes not work?',['../md_docs_2troubleshooting.html#autotoc_md132',1,'']]],
  ['documentation_12',['Documentation',['../index.html#autotoc_md8',1,'📚 Documentation'],['../md_docs_2index.html',1,'HF-PCAL95555 Documentation']]],
  ['documentation_20structure_13',['📚 Documentation Structure',['../md_docs_2index.html#autotoc_md77',1,'']]],
  ['don_20t_20forget_20the_20template_20parameter_14',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md109',1,'']]],
  ['don_20t_20use_20virtual_20functions_15',['❌ Don&apos;t Use Virtual Functions',['../md_docs_2platform__integration.html#autotoc_md107',1,'']]],
  ['down_16',['Down',['../md_docs_2api__reference.html#autotoc_md19',1,'Pull-up/Pull-down'],['../md_docs_2troubleshooting.html#autotoc_md135',1,'Q: What&apos;s the difference between pull-up and pull-down?']]],
  ['drive_20strength_17',['Drive Strength',['../md_docs_2api__reference.html#autotoc_md20',1,'Drive Strength'],['../md_docs_2configuration.html#autotoc_md39',1,'Drive Strength'],['../md_docs_2examples.html#autotoc_md59',1,'Example 5: Drive Strength']]],
  ['drive_20strength_20levels_20are_20available_18',['Q: What drive strength levels are available?',['../md_docs_2troubleshooting.html#autotoc_md136',1,'']]],
  ['driven_20inputs_19',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md51',1,'']]],
  ['driver_20',['HF-PCAL95555 Driver',['../index.html',1,'']]],
  ['driver_20instance_21',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md119',1,'']]],
  ['dynamic_20address_20changes_22',['Dynamic Address Changes',['../md_docs_2configuration.html#autotoc_md32',1,'']]]
];
