var searchData=
[
  ['s_20the_20difference_20between_20pull_20up_20and_20pull_20down_0',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md129',1,'']]],
  ['safety_1',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md90',1,'']]],
  ['settings_2',['Recommended Settings',['../md_docs_2configuration.html#autotoc_md44',1,'']]],
  ['setup_3',['Hardware Setup',['../md_docs_2hardware__setup.html',1,'']]],
  ['single_20pcal9555a_4',['Single PCAL9555A',['../md_docs_2hardware__setup.html#autotoc_md65',1,'']]],
  ['source_20code_5',['Source Code',['../md_docs_2api__reference.html#autotoc_md12',1,'']]],
  ['specific_20examples_6',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md96',1,'']]],
  ['start_7',['Start',['../index.html#autotoc_md4',1,'🚀 Quick Start'],['../md_docs_2quickstart.html',1,'Quick Start']]],
  ['started_20strong_8',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md72',1,'']]],
  ['states_9',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md123',1,'']]],
  ['status_10',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md43',1,'']]],
  ['step_201_3a_20create_20your_20implementation_20class_11',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md95',1,'']]],
  ['step_201_3a_20include_20the_20header_12',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md111',1,'']]],
  ['step_202_3a_20implement_20the_20i2c_20interface_13',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md112',1,'']]],
  ['step_202_3a_20platform_20specific_20examples_14',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md96',1,'']]],
  ['step_203_3a_20create_20driver_20instance_15',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md113',1,'']]],
  ['step_204_3a_20initialize_16',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md114',1,'']]],
  ['step_205_3a_20configure_20and_20use_20pins_17',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md115',1,'']]],
  ['step_20by_20step_20explanation_18',['Step-by-Step Explanation',['../md_docs_2quickstart.html#autotoc_md110',1,'']]],
  ['steps_19',['Steps',['../md_docs_2platform__integration.html#autotoc_md94',1,'Implementation Steps'],['../md_docs_2configuration.html#autotoc_md48',1,'Next Steps'],['../md_docs_2hardware__setup.html#autotoc_md69',1,'Next Steps'],['../md_docs_2installation.html#autotoc_md83',1,'Next Steps'],['../md_docs_2platform__integration.html#autotoc_md106',1,'Next Steps'],['../md_docs_2quickstart.html#autotoc_md118',1,'Next Steps']]],
  ['stm32_20hal_20',['STM32 (HAL)',['../md_docs_2platform__integration.html#autotoc_md98',1,'']]],
  ['strength_21',['Strength',['../md_docs_2api__reference.html#autotoc_md20',1,'Drive Strength'],['../md_docs_2configuration.html#autotoc_md36',1,'Drive Strength'],['../md_docs_2examples.html#autotoc_md53',1,'Example 5: Drive Strength']]],
  ['strong_20compile_20time_20polymorphism_20strong_22',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md88',1,'']]],
  ['strong_20getting_20started_20strong_23',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md72',1,'']]],
  ['strong_20integration_20strong_24',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md73',1,'']]],
  ['strong_20memory_20efficiency_20strong_25',['3. &lt;strong&gt;Memory Efficiency&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md89',1,'']]],
  ['strong_20reference_20strong_26',['&lt;strong&gt;Reference&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md74',1,'']]],
  ['strong_20troubleshooting_20strong_27',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md75',1,'']]],
  ['strong_20zero_20runtime_20overhead_20strong_28',['1. &lt;strong&gt;Zero Runtime Overhead&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md87',1,'']]],
  ['structure_29',['📚 Documentation Structure',['../md_docs_2index.html#autotoc_md71',1,'']]],
  ['submodule_30',['Option 2: Git Submodule',['../md_docs_2installation.html#autotoc_md81',1,'']]]
];
