var searchData=
[
  ['t_20forget_20the_20template_20parameter_0',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md123',1,'']]],
  ['t_20use_20virtual_20functions_1',['❌ Don&apos;t Use Virtual Functions',['../md_docs_2platform__integration.html#autotoc_md121',1,'']]],
  ['table_2',['Address Pin Configuration Table',['../md_docs_2configuration.html#autotoc_md39',1,'']]],
  ['template_20parameter_3',['Template Parameter',['../md_docs_2platform__integration.html#autotoc_md124',1,'✅ Correct Template Parameter'],['../md_docs_2platform__integration.html#autotoc_md123',1,'❌ Don&apos;t Forget the Template Parameter']]],
  ['template_20pattern_4',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md105',1,'']]],
  ['test_20suite_20tt_20pcal95555_5fcomprehensive_5ftest_20tt_5',['Comprehensive Test Suite (&lt;tt&gt;pcal95555_comprehensive_test&lt;/tt&gt;)',['../index.html#autotoc_md11',1,'']]],
  ['test_20wiring_6',['Interactive test wiring',['../index.html#autotoc_md16',1,'']]],
  ['testing_20your_20implementation_7',['Testing Your Implementation',['../md_docs_2platform__integration.html#autotoc_md125',1,'']]],
  ['the_20difference_20between_20pull_20up_20and_20pull_20down_8',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md152',1,'']]],
  ['the_20driver_20and_20use_20it_9',['2. Create the driver and use it',['../index.html#autotoc_md5',1,'']]],
  ['the_20examples_10',['Running the Examples',['../md_docs_2examples.html#autotoc_md70',1,'']]],
  ['the_20header_11',['The Header',['../md_docs_2installation.html#autotoc_md102',1,'Including the Header'],['../md_docs_2quickstart.html#autotoc_md131',1,'Step 1: Include the Header']]],
  ['the_20i2c_20interface_12',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['the_20i2c_20interface_20for_20your_20platform_13',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['the_20template_20parameter_14',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md123',1,'']]],
  ['time_20polymorphism_20strong_15',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['troubleshooting_16',['Troubleshooting',['../md_docs_2troubleshooting.html',1,'Troubleshooting'],['../md_docs_2quickstart.html#autotoc_md137',1,'Troubleshooting']]],
  ['troubleshooting_20strong_17',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md95',1,'']]],
  ['tt_20pcal95555_20i2ctype_20tt_18',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md21',1,'']]],
  ['tt_20pcal95555_5fcomprehensive_5ftest_20tt_19',['Comprehensive Test Suite (&lt;tt&gt;pcal95555_comprehensive_test&lt;/tt&gt;)',['../index.html#autotoc_md11',1,'']]],
  ['tt_20pcal95555_5fled_5fanimation_20tt_20',['LED Animation Demo (&lt;tt&gt;pcal95555_led_animation&lt;/tt&gt;)',['../index.html#autotoc_md12',1,'']]],
  ['type_20safety_21',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md110',1,'']]],
  ['types_22',['Types',['../md_docs_2api__reference.html#autotoc_md35',1,'']]]
];
