var searchData=
[
  ['s_20the_20difference_20between_20pull_20up_20and_20pull_20down_0',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md132',1,'']]],
  ['safety_1',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md93',1,'']]],
  ['setinterruptcallback_20callback_20tt_2',['&lt;tt&gt;SetInterruptCallback(callback)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md26',1,'']]],
  ['setoutputmode_20port_5f0_5fod_20port_5f1_5fod_20tt_3',['&lt;tt&gt;SetOutputMode(port_0_od, port_1_od)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md28',1,'']]],
  ['setpindirection_20pin_20dir_20tt_4',['&lt;tt&gt;SetPinDirection(pin, dir)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md19',1,'']]],
  ['setpulldirection_20pin_20pull_5fup_20tt_5',['&lt;tt&gt;SetPullDirection(pin, pull_up)&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md23',1,'']]],
  ['settings_6',['Recommended Settings',['../md_docs_2configuration.html#autotoc_md47',1,'']]],
  ['setup_7',['Hardware Setup',['../md_docs_2hardware__setup.html',1,'']]],
  ['single_20pcal9555a_8',['Single PCAL9555A',['../md_docs_2hardware__setup.html#autotoc_md68',1,'']]],
  ['source_20code_9',['Source Code',['../md_docs_2api__reference.html#autotoc_md12',1,'']]],
  ['specific_20examples_10',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md99',1,'']]],
  ['start_11',['Start',['../index.html#autotoc_md4',1,'🚀 Quick Start'],['../md_docs_2quickstart.html',1,'Quick Start']]],
  ['started_20strong_12',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md75',1,'']]],
  ['states_13',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md126',1,'']]],
  ['status_14',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md46',1,'']]],
  ['step_201_3a_20create_20your_20implementation_20class_15',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md98',1,'']]],
  ['step_201_3a_20include_20the_20header_16',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md114',1,'']]],
  ['step_202_3a_20implement_20the_20i2c_20interface_17',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md115',1,'']]],
  ['step_202_3a_20platform_20specific_20examples_18',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md99',1,'']]],
  ['step_203_3a_20create_20driver_20instance_19',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md116',1,'']]],
  ['step_204_3a_20initialize_20',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md117',1,'']]],
  ['step_205_3a_20configure_20and_20use_20pins_21',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md118',1,'']]],
  ['step_20by_20step_20explanation_22',['Step-by-Step Explanation',['../md_docs_2quickstart.html#autotoc_md113',1,'']]],
  ['steps_23',['Steps',['../md_docs_2platform__integration.html#autotoc_md97',1,'Implementation Steps'],['../md_docs_2configuration.html#autotoc_md51',1,'Next Steps'],['../md_docs_2hardware__setup.html#autotoc_md72',1,'Next Steps'],['../md_docs_2installation.html#autotoc_md86',1,'Next Steps'],['../md_docs_2platform__integration.html#autotoc_md109',1,'Next Steps'],['../md_docs_2quickstart.html#autotoc_md121',1,'Next Steps']]],
  ['stm32_20hal_24',['STM32 (HAL)',['../md_docs_2platform__integration.html#autotoc_md101',1,'']]],
  ['strength_25',['Strength',['../md_docs_2configuration.html#autotoc_md39',1,'Drive Strength'],['../md_docs_2examples.html#autotoc_md56',1,'Example 5: Drive Strength']]],
  ['strong_20compile_20time_20polymorphism_20strong_26',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md91',1,'']]],
  ['strong_20getting_20started_20strong_27',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md75',1,'']]],
  ['strong_20integration_20strong_28',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md76',1,'']]],
  ['strong_20memory_20efficiency_20strong_29',['3. &lt;strong&gt;Memory Efficiency&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md92',1,'']]],
  ['strong_20reference_20strong_30',['&lt;strong&gt;Reference&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md77',1,'']]],
  ['strong_20troubleshooting_20strong_31',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md78',1,'']]],
  ['strong_20zero_20runtime_20overhead_20strong_32',['1. &lt;strong&gt;Zero Runtime Overhead&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md90',1,'']]],
  ['structure_33',['📚 Documentation Structure',['../md_docs_2index.html#autotoc_md74',1,'']]],
  ['submodule_34',['Option 2: Git Submodule',['../md_docs_2installation.html#autotoc_md84',1,'']]]
];
