var searchData=
[
  ['s3_20pca9555_20pcal9555a_0',['Minimal wiring (ESP32-S3 + PCA9555/PCAL9555A)',['../index.html#autotoc_md14',1,'']]],
  ['safety_1',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md110',1,'']]],
  ['settings_2',['Recommended Settings',['../md_docs_2configuration.html#autotoc_md57',1,'']]],
  ['setup_3',['Setup',['../md_docs_2configuration.html#autotoc_md54',1,'Basic Interrupt Setup'],['../md_docs_2hardware__setup.html',1,'Hardware Setup'],['../index.html#autotoc_md13',1,'Hardware Setup']]],
  ['single_20device_4',['Single Device',['../md_docs_2hardware__setup.html#autotoc_md85',1,'']]],
  ['source_20code_5',['Source Code',['../md_docs_2api__reference.html#autotoc_md19',1,'']]],
  ['specific_20examples_6',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md116',1,'']]],
  ['start_7',['Start',['../md_docs_2quickstart.html',1,'Quick Start'],['../index.html#autotoc_md3',1,'Quick Start']]],
  ['started_20strong_8',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md92',1,'']]],
  ['states_9',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['status_10',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md56',1,'']]],
  ['step_201_3a_20create_20your_20implementation_20class_11',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md115',1,'']]],
  ['step_201_3a_20include_20the_20header_12',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md131',1,'']]],
  ['step_202_3a_20implement_20the_20i2c_20interface_13',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['step_202_3a_20platform_20specific_20examples_14',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md116',1,'']]],
  ['step_203_3a_20create_20driver_20instance_15',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md133',1,'']]],
  ['step_204_3a_20initialize_16',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md134',1,'']]],
  ['step_205_3a_20configure_20and_20use_20pins_17',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md135',1,'']]],
  ['step_20by_20step_20explanation_18',['Step-by-Step Explanation',['../md_docs_2quickstart.html#autotoc_md130',1,'']]],
  ['steps_19',['Steps',['../md_docs_2platform__integration.html#autotoc_md114',1,'Implementation Steps'],['../md_docs_2configuration.html#autotoc_md61',1,'Next Steps'],['../md_docs_2examples.html#autotoc_md73',1,'Next Steps'],['../md_docs_2hardware__setup.html#autotoc_md89',1,'Next Steps'],['../md_docs_2installation.html#autotoc_md103',1,'Next Steps'],['../md_docs_2platform__integration.html#autotoc_md126',1,'Next Steps'],['../md_docs_2quickstart.html#autotoc_md138',1,'Next Steps']]],
  ['stm32_20hal_20',['STM32 (HAL)',['../md_docs_2platform__integration.html#autotoc_md118',1,'']]],
  ['strength_20pcal9555a_20only_21',['Strength PCAL9555A only',['../md_docs_2api__reference.html#autotoc_md27',1,'Drive Strength (PCAL9555A only)'],['../md_docs_2configuration.html#autotoc_md47',1,'Drive Strength (PCAL9555A only)'],['../md_docs_2examples.html#autotoc_md68',1,'Example 5: Drive Strength (PCAL9555A only)']]],
  ['strong_20compile_20time_20polymorphism_20strong_22',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['strong_20getting_20started_20strong_23',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md92',1,'']]],
  ['strong_20integration_20strong_24',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md93',1,'']]],
  ['strong_20memory_20efficiency_20strong_25',['3. &lt;strong&gt;Memory Efficiency&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md109',1,'']]],
  ['strong_20reference_20strong_26',['&lt;strong&gt;Reference&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md94',1,'']]],
  ['strong_20troubleshooting_20strong_27',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md95',1,'']]],
  ['strong_20zero_20runtime_20overhead_20strong_28',['1. &lt;strong&gt;Zero Runtime Overhead&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md107',1,'']]],
  ['structure_29',['📚 Documentation Structure',['../md_docs_2index.html#autotoc_md91',1,'']]],
  ['submodule_30',['Option 2: Git Submodule',['../md_docs_2installation.html#autotoc_md101',1,'']]],
  ['suite_20tt_20pcal95555_5fcomprehensive_5ftest_20tt_31',['Comprehensive Test Suite (&lt;tt&gt;pcal95555_comprehensive_test&lt;/tt&gt;)',['../index.html#autotoc_md11',1,'']]]
];
