var searchData=
[
  ['s_20the_20difference_20between_20pull_20up_20and_20pull_20down_0',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md135',1,'']]],
  ['safety_1',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md96',1,'']]],
  ['settings_2',['Recommended Settings',['../md_docs_2configuration.html#autotoc_md48',1,'']]],
  ['setup_3',['Setup',['../md_docs_2configuration.html#autotoc_md45',1,'Basic Interrupt Setup'],['../md_docs_2hardware__setup.html',1,'Hardware Setup']]],
  ['single_20pcal9555a_4',['Single PCAL9555A',['../md_docs_2hardware__setup.html#autotoc_md71',1,'']]],
  ['source_20code_5',['Source Code',['../md_docs_2api__reference.html#autotoc_md12',1,'']]],
  ['specific_20examples_6',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md102',1,'']]],
  ['start_7',['Start',['../index.html#autotoc_md4',1,'🚀 Quick Start'],['../md_docs_2quickstart.html',1,'Quick Start']]],
  ['started_20strong_8',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md78',1,'']]],
  ['states_9',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md129',1,'']]],
  ['status_10',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md47',1,'']]],
  ['step_201_3a_20create_20your_20implementation_20class_11',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md101',1,'']]],
  ['step_201_3a_20include_20the_20header_12',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md117',1,'']]],
  ['step_202_3a_20implement_20the_20i2c_20interface_13',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md118',1,'']]],
  ['step_202_3a_20platform_20specific_20examples_14',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md102',1,'']]],
  ['step_203_3a_20create_20driver_20instance_15',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md119',1,'']]],
  ['step_204_3a_20initialize_16',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md120',1,'']]],
  ['step_205_3a_20configure_20and_20use_20pins_17',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md121',1,'']]],
  ['step_20by_20step_20explanation_18',['Step-by-Step Explanation',['../md_docs_2quickstart.html#autotoc_md116',1,'']]],
  ['steps_19',['Steps',['../md_docs_2platform__integration.html#autotoc_md100',1,'Implementation Steps'],['../md_docs_2configuration.html#autotoc_md52',1,'Next Steps'],['../md_docs_2hardware__setup.html#autotoc_md75',1,'Next Steps'],['../md_docs_2installation.html#autotoc_md89',1,'Next Steps'],['../md_docs_2platform__integration.html#autotoc_md112',1,'Next Steps'],['../md_docs_2quickstart.html#autotoc_md124',1,'Next Steps']]],
  ['stm32_20hal_20',['STM32 (HAL)',['../md_docs_2platform__integration.html#autotoc_md104',1,'']]],
  ['strength_21',['Strength',['../md_docs_2api__reference.html#autotoc_md20',1,'Drive Strength'],['../md_docs_2configuration.html#autotoc_md39',1,'Drive Strength'],['../md_docs_2examples.html#autotoc_md59',1,'Example 5: Drive Strength']]],
  ['strength_20levels_20are_20available_22',['Q: What drive strength levels are available?',['../md_docs_2troubleshooting.html#autotoc_md136',1,'']]],
  ['strong_20compile_20time_20polymorphism_20strong_23',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md94',1,'']]],
  ['strong_20getting_20started_20strong_24',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md78',1,'']]],
  ['strong_20integration_20strong_25',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md79',1,'']]],
  ['strong_20memory_20efficiency_20strong_26',['3. &lt;strong&gt;Memory Efficiency&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md95',1,'']]],
  ['strong_20reference_20strong_27',['&lt;strong&gt;Reference&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md80',1,'']]],
  ['strong_20troubleshooting_20strong_28',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md81',1,'']]],
  ['strong_20zero_20runtime_20overhead_20strong_29',['1. &lt;strong&gt;Zero Runtime Overhead&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md93',1,'']]],
  ['structure_30',['📚 Documentation Structure',['../md_docs_2index.html#autotoc_md77',1,'']]],
  ['submodule_31',['Option 2: Git Submodule',['../md_docs_2installation.html#autotoc_md87',1,'']]]
];
