var searchData=
[
  ['i_20check_20for_20errors_0',['Q: How do I check for errors?',['../md_docs_2troubleshooting.html#autotoc_md161',1,'']]],
  ['i_20know_20which_20chip_20i_20have_20pca9555_20vs_20pcal9555a_1',['Q: How do I know which chip I have (PCA9555 vs PCAL9555A)?',['../md_docs_2troubleshooting.html#autotoc_md158',1,'']]],
  ['i_20o_2',['Pin I/O',['../md_docs_2api__reference.html#autotoc_md25',1,'']]],
  ['i_20use_20interrupts_3',['Q: How do I use interrupts?',['../md_docs_2troubleshooting.html#autotoc_md156',1,'']]],
  ['i_20use_20multiple_20devices_4',['Q: Can I use multiple devices?',['../md_docs_2troubleshooting.html#autotoc_md157',1,'']]],
  ['i2c_20address_20configuration_5',['I2C Address Configuration',['../md_docs_2configuration.html#autotoc_md45',1,'']]],
  ['i2c_20bus_20configuration_6',['I2C Bus Configuration',['../md_docs_2hardware__setup.html#autotoc_md89',1,'']]],
  ['i2c_20communication_20failures_7',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md149',1,'']]],
  ['i2c_20configuration_8',['I2C Configuration',['../md_docs_2hardware__setup.html#autotoc_md87',1,'']]],
  ['i2c_20connections_9',['Basic I2C Connections',['../md_docs_2hardware__setup.html#autotoc_md83',1,'']]],
  ['i2c_20interface_10',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md139',1,'']]],
  ['i2c_20interface_20for_20your_20platform_11',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['i2ctype_20tt_12',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md21',1,'']]],
  ['idf_13',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md124',1,'']]],
  ['idf_20integration_14',['ESP-IDF Integration',['../md_docs_2cmake__integration.html#autotoc_md38',1,'']]],
  ['if_20needed_15',['2. Override the Driver Root (if needed)',['../md_docs_2cmake__integration.html#autotoc_md40',1,'']]],
  ['implement_20the_20i2c_20interface_16',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md139',1,'']]],
  ['implement_20the_20i2c_20interface_20for_20your_20platform_17',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['implementation_18',['Implementation',['../md_docs_2platform__integration.html#autotoc_md129',1,'✅ Correct CRTP Implementation'],['../md_docs_2platform__integration.html#autotoc_md132',1,'Testing Your Implementation']]],
  ['implementation_20class_19',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md122',1,'']]],
  ['implementation_20steps_20',['Implementation Steps',['../md_docs_2platform__integration.html#autotoc_md121',1,'']]],
  ['include_20and_20use_21',['4. Include and Use',['../md_docs_2cmake__integration.html#autotoc_md42',1,'']]],
  ['include_20the_20header_22',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md138',1,'']]],
  ['including_20the_20header_23',['Including the Header',['../md_docs_2installation.html#autotoc_md109',1,'']]],
  ['incorrect_20pin_20states_24',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md150',1,'']]],
  ['initialization_25',['Initialization',['../md_docs_2api__reference.html#autotoc_md23',1,'']]],
  ['initialize_26',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md141',1,'']]],
  ['input_20latch_20pcal9555a_20only_27',['Input Latch (PCAL9555A only)',['../md_docs_2api__reference.html#autotoc_md31',1,'']]],
  ['input_20pins_28',['For Input Pins',['../md_docs_2configuration.html#autotoc_md65',1,'']]],
  ['inputs_29',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md67',1,'']]],
  ['installation_30',['Installation',['../md_docs_2installation.html',1,'']]],
  ['instance_31',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md140',1,'']]],
  ['instead_20of_20virtual_20functions_32',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md113',1,'']]],
  ['integration_33',['Integration',['../md_docs_2cmake__integration.html#autotoc_md38',1,'ESP-IDF Integration'],['../md_docs_2installation.html#autotoc_md106',1,'Integration']]],
  ['integration_20guide_34',['Integration Guide',['../md_docs_2cmake__integration.html',1,'PCAL95555 — CMake Integration Guide'],['../md_docs_2platform__integration.html',1,'Platform Integration Guide']]],
  ['integration_20strong_35',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md100',1,'']]],
  ['interactive_20test_20wiring_36',['Interactive test wiring',['../index.html#autotoc_md16',1,'']]],
  ['interface_37',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md139',1,'']]],
  ['interface_20definition_38',['Interface Definition',['../md_docs_2platform__integration.html#autotoc_md120',1,'']]],
  ['interface_20for_20your_20platform_39',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['interrupt_20callback_40',['Global Interrupt Callback',['../md_docs_2examples.html#autotoc_md74',1,'']]],
  ['interrupt_20callbacks_41',['Per-Pin Interrupt Callbacks',['../md_docs_2configuration.html#autotoc_md62',1,'']]],
  ['interrupt_20configuration_42',['Interrupt Configuration',['../md_docs_2configuration.html#autotoc_md60',1,'']]],
  ['interrupt_20driven_20inputs_43',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md67',1,'']]],
  ['interrupt_20handling_44',['Example 3: Interrupt Handling',['../md_docs_2examples.html#autotoc_md72',1,'']]],
  ['interrupt_20pin_20optional_45',['Interrupt Pin (Optional)',['../md_docs_2hardware__setup.html#autotoc_md94',1,'']]],
  ['interrupt_20setup_46',['Basic Interrupt Setup',['../md_docs_2configuration.html#autotoc_md61',1,'']]],
  ['interrupt_20status_47',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md63',1,'']]],
  ['interrupts_48',['Interrupts',['../md_docs_2examples.html#autotoc_md73',1,'Configure Multiple Interrupts'],['../md_docs_2api__reference.html#autotoc_md28',1,'Interrupts'],['../md_docs_2troubleshooting.html#autotoc_md156',1,'Q: How do I use interrupts?']]],
  ['invalid_20address_20invalidaddress_49',['Error: Invalid Address (InvalidAddress)',['../md_docs_2troubleshooting.html#autotoc_md152',1,'']]],
  ['invalidaddress_50',['Error: Invalid Address (InvalidAddress)',['../md_docs_2troubleshooting.html#autotoc_md152',1,'']]],
  ['inversion_51',['Polarity Inversion',['../md_docs_2configuration.html#autotoc_md56',1,'']]],
  ['it_52',['2. Create the driver and use it',['../index.html#autotoc_md5',1,'']]]
];
