var searchData=
[
  ['i_20o_0',['Pin I/O',['../md_docs_2api__reference.html#autotoc_md18',1,'']]],
  ['i_20use_20interrupts_1',['Q: How do I use interrupts?',['../md_docs_2troubleshooting.html#autotoc_md127',1,'']]],
  ['i_20use_20multiple_20pcal9555a_20devices_2',['Q: Can I use multiple PCAL9555A devices?',['../md_docs_2troubleshooting.html#autotoc_md128',1,'']]],
  ['i2c_20address_20configuration_3',['I2C Address Configuration',['../md_docs_2configuration.html#autotoc_md29',1,'']]],
  ['i2c_20bus_20configuration_4',['I2C Bus Configuration',['../md_docs_2hardware__setup.html#autotoc_md62',1,'']]],
  ['i2c_20communication_20failures_5',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md122',1,'']]],
  ['i2c_20configuration_6',['I2C Configuration',['../md_docs_2hardware__setup.html#autotoc_md60',1,'']]],
  ['i2c_20connections_7',['Basic I2C Connections',['../md_docs_2hardware__setup.html#autotoc_md56',1,'']]],
  ['i2c_20interface_8',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md112',1,'']]],
  ['i2ctype_20tt_9',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md14',1,'']]],
  ['idf_10',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md97',1,'']]],
  ['implement_20the_20i2c_20interface_11',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md112',1,'']]],
  ['implementation_12',['Implementation',['../md_docs_2platform__integration.html#autotoc_md102',1,'✅ Correct CRTP Implementation'],['../md_docs_2platform__integration.html#autotoc_md105',1,'Testing Your Implementation']]],
  ['implementation_20class_13',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md95',1,'']]],
  ['implementation_20steps_14',['Implementation Steps',['../md_docs_2platform__integration.html#autotoc_md94',1,'']]],
  ['include_20the_20header_15',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md111',1,'']]],
  ['including_20the_20header_16',['Including the Header',['../md_docs_2installation.html#autotoc_md82',1,'']]],
  ['incorrect_20pin_20states_17',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md123',1,'']]],
  ['initialization_18',['Initialization',['../md_docs_2api__reference.html#autotoc_md16',1,'']]],
  ['initialize_19',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md114',1,'']]],
  ['input_20latch_20',['Input Latch',['../md_docs_2api__reference.html#autotoc_md24',1,'']]],
  ['input_20pins_21',['For Input Pins',['../md_docs_2configuration.html#autotoc_md45',1,'']]],
  ['inputs_22',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md47',1,'']]],
  ['installation_23',['Installation',['../index.html#autotoc_md5',1,'🔧 Installation'],['../md_docs_2installation.html',1,'Installation']]],
  ['instance_24',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md113',1,'']]],
  ['instead_20of_20virtual_20functions_25',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md86',1,'']]],
  ['integration_26',['Integration',['../md_docs_2installation.html#autotoc_md79',1,'']]],
  ['integration_20guide_27',['Platform Integration Guide',['../md_docs_2platform__integration.html',1,'']]],
  ['integration_20strong_28',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md73',1,'']]],
  ['interface_29',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md112',1,'']]],
  ['interface_20definition_30',['Interface Definition',['../md_docs_2platform__integration.html#autotoc_md93',1,'']]],
  ['interrupt_20configuration_31',['Interrupt Configuration',['../md_docs_2configuration.html#autotoc_md41',1,'']]],
  ['interrupt_20driven_20inputs_32',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md47',1,'']]],
  ['interrupt_20handling_33',['Example 3: Interrupt Handling',['../md_docs_2examples.html#autotoc_md52',1,'']]],
  ['interrupt_20pin_20optional_34',['Interrupt Pin (Optional)',['../md_docs_2hardware__setup.html#autotoc_md67',1,'']]],
  ['interrupt_20status_35',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md43',1,'']]],
  ['interrupts_36',['Interrupts',['../md_docs_2configuration.html#autotoc_md42',1,'Enable Interrupts'],['../md_docs_2api__reference.html#autotoc_md21',1,'Interrupts'],['../md_docs_2troubleshooting.html#autotoc_md127',1,'Q: How do I use interrupts?']]],
  ['inversion_37',['Polarity Inversion',['../md_docs_2configuration.html#autotoc_md38',1,'']]]
];
