var searchData=
[
  ['s_20the_20difference_20between_20pull_20up_20and_20pull_20down_0',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md152',1,'']]],
  ['s3_20pca9555_20pcal9555a_1',['Minimal wiring (ESP32-S3 + PCA9555/PCAL9555A)',['../index.html#autotoc_md14',1,'']]],
  ['safety_2',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md110',1,'']]],
  ['settings_3',['Recommended Settings',['../md_docs_2configuration.html#autotoc_md57',1,'']]],
  ['setup_4',['Setup',['../md_docs_2configuration.html#autotoc_md54',1,'Basic Interrupt Setup'],['../md_docs_2hardware__setup.html',1,'Hardware Setup'],['../index.html#autotoc_md13',1,'Hardware Setup']]],
  ['shows_20unknown_5',['Error: ChipVariant Shows &quot;Unknown&quot;',['../md_docs_2troubleshooting.html#autotoc_md146',1,'']]],
  ['single_20device_6',['Single Device',['../md_docs_2hardware__setup.html#autotoc_md85',1,'']]],
  ['source_20code_7',['Source Code',['../md_docs_2api__reference.html#autotoc_md19',1,'']]],
  ['specific_20examples_8',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md116',1,'']]],
  ['start_9',['Start',['../md_docs_2quickstart.html',1,'Quick Start'],['../index.html#autotoc_md3',1,'Quick Start']]],
  ['started_20strong_10',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md92',1,'']]],
  ['states_11',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['status_12',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md56',1,'']]],
  ['step_201_3a_20create_20your_20implementation_20class_13',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md115',1,'']]],
  ['step_201_3a_20include_20the_20header_14',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md131',1,'']]],
  ['step_202_3a_20implement_20the_20i2c_20interface_15',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['step_202_3a_20platform_20specific_20examples_16',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md116',1,'']]],
  ['step_203_3a_20create_20driver_20instance_17',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md133',1,'']]],
  ['step_204_3a_20initialize_18',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md134',1,'']]],
  ['step_205_3a_20configure_20and_20use_20pins_19',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md135',1,'']]],
  ['step_20by_20step_20explanation_20',['Step-by-Step Explanation',['../md_docs_2quickstart.html#autotoc_md130',1,'']]],
  ['steps_21',['Steps',['../md_docs_2platform__integration.html#autotoc_md114',1,'Implementation Steps'],['../md_docs_2configuration.html#autotoc_md61',1,'Next Steps'],['../md_docs_2examples.html#autotoc_md73',1,'Next Steps'],['../md_docs_2hardware__setup.html#autotoc_md89',1,'Next Steps'],['../md_docs_2installation.html#autotoc_md103',1,'Next Steps'],['../md_docs_2platform__integration.html#autotoc_md126',1,'Next Steps'],['../md_docs_2quickstart.html#autotoc_md138',1,'Next Steps']]],
  ['stm32_20hal_22',['STM32 (HAL)',['../md_docs_2platform__integration.html#autotoc_md118',1,'']]],
  ['strength_20levels_20are_20available_23',['Q: What drive strength levels are available?',['../md_docs_2troubleshooting.html#autotoc_md153',1,'']]],
  ['strength_20pcal9555a_20only_24',['Strength PCAL9555A only',['../md_docs_2api__reference.html#autotoc_md27',1,'Drive Strength (PCAL9555A only)'],['../md_docs_2configuration.html#autotoc_md47',1,'Drive Strength (PCAL9555A only)'],['../md_docs_2examples.html#autotoc_md68',1,'Example 5: Drive Strength (PCAL9555A only)']]],
  ['strong_20compile_20time_20polymorphism_20strong_25',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['strong_20getting_20started_20strong_26',['&lt;strong&gt;Getting Started&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md92',1,'']]],
  ['strong_20integration_20strong_27',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md93',1,'']]],
  ['strong_20memory_20efficiency_20strong_28',['3. &lt;strong&gt;Memory Efficiency&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md109',1,'']]],
  ['strong_20reference_20strong_29',['&lt;strong&gt;Reference&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md94',1,'']]],
  ['strong_20troubleshooting_20strong_30',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md95',1,'']]],
  ['strong_20zero_20runtime_20overhead_20strong_31',['1. &lt;strong&gt;Zero Runtime Overhead&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md107',1,'']]],
  ['structure_32',['📚 Documentation Structure',['../md_docs_2index.html#autotoc_md91',1,'']]],
  ['submodule_33',['Option 2: Git Submodule',['../md_docs_2installation.html#autotoc_md101',1,'']]],
  ['suite_20tt_20pcal95555_5fcomprehensive_5ftest_20tt_34',['Comprehensive Test Suite (&lt;tt&gt;pcal95555_comprehensive_test&lt;/tt&gt;)',['../index.html#autotoc_md11',1,'']]]
];
