var searchData=
[
  ['i_20check_20for_20errors_0',['Q: How do I check for errors?',['../md_docs_2troubleshooting.html#autotoc_md154',1,'']]],
  ['i_20know_20which_20chip_20i_20have_20pca9555_20vs_20pcal9555a_1',['Q: How do I know which chip I have (PCA9555 vs PCAL9555A)?',['../md_docs_2troubleshooting.html#autotoc_md151',1,'']]],
  ['i_20o_2',['Pin I/O',['../md_docs_2api__reference.html#autotoc_md25',1,'']]],
  ['i_20use_20interrupts_3',['Q: How do I use interrupts?',['../md_docs_2troubleshooting.html#autotoc_md149',1,'']]],
  ['i_20use_20multiple_20devices_4',['Q: Can I use multiple devices?',['../md_docs_2troubleshooting.html#autotoc_md150',1,'']]],
  ['i2c_20address_20configuration_5',['I2C Address Configuration',['../md_docs_2configuration.html#autotoc_md38',1,'']]],
  ['i2c_20bus_20configuration_6',['I2C Bus Configuration',['../md_docs_2hardware__setup.html#autotoc_md82',1,'']]],
  ['i2c_20communication_20failures_7',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md142',1,'']]],
  ['i2c_20configuration_8',['I2C Configuration',['../md_docs_2hardware__setup.html#autotoc_md80',1,'']]],
  ['i2c_20connections_9',['Basic I2C Connections',['../md_docs_2hardware__setup.html#autotoc_md76',1,'']]],
  ['i2c_20interface_10',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['i2c_20interface_20for_20your_20platform_11',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['i2ctype_20tt_12',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md21',1,'']]],
  ['idf_13',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md117',1,'']]],
  ['implement_20the_20i2c_20interface_14',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['implement_20the_20i2c_20interface_20for_20your_20platform_15',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['implementation_16',['Implementation',['../md_docs_2platform__integration.html#autotoc_md122',1,'✅ Correct CRTP Implementation'],['../md_docs_2platform__integration.html#autotoc_md125',1,'Testing Your Implementation']]],
  ['implementation_20class_17',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md115',1,'']]],
  ['implementation_20steps_18',['Implementation Steps',['../md_docs_2platform__integration.html#autotoc_md114',1,'']]],
  ['include_20the_20header_19',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md131',1,'']]],
  ['including_20the_20header_20',['Including the Header',['../md_docs_2installation.html#autotoc_md102',1,'']]],
  ['incorrect_20pin_20states_21',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['initialization_22',['Initialization',['../md_docs_2api__reference.html#autotoc_md23',1,'']]],
  ['initialize_23',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md134',1,'']]],
  ['input_20latch_20pcal9555a_20only_24',['Input Latch (PCAL9555A only)',['../md_docs_2api__reference.html#autotoc_md31',1,'']]],
  ['input_20pins_25',['For Input Pins',['../md_docs_2configuration.html#autotoc_md58',1,'']]],
  ['inputs_26',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md60',1,'']]],
  ['installation_27',['Installation',['../md_docs_2installation.html',1,'']]],
  ['instance_28',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md133',1,'']]],
  ['instead_20of_20virtual_20functions_29',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md106',1,'']]],
  ['integration_30',['Integration',['../md_docs_2installation.html#autotoc_md99',1,'']]],
  ['integration_20guide_31',['Platform Integration Guide',['../md_docs_2platform__integration.html',1,'']]],
  ['integration_20strong_32',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md93',1,'']]],
  ['interactive_20test_20wiring_33',['Interactive test wiring',['../index.html#autotoc_md16',1,'']]],
  ['interface_34',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['interface_20definition_35',['Interface Definition',['../md_docs_2platform__integration.html#autotoc_md113',1,'']]],
  ['interface_20for_20your_20platform_36',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['interrupt_20callback_37',['Global Interrupt Callback',['../md_docs_2examples.html#autotoc_md67',1,'']]],
  ['interrupt_20callbacks_38',['Per-Pin Interrupt Callbacks',['../md_docs_2configuration.html#autotoc_md55',1,'']]],
  ['interrupt_20configuration_39',['Interrupt Configuration',['../md_docs_2configuration.html#autotoc_md53',1,'']]],
  ['interrupt_20driven_20inputs_40',['For Interrupt-Driven Inputs',['../md_docs_2configuration.html#autotoc_md60',1,'']]],
  ['interrupt_20handling_41',['Example 3: Interrupt Handling',['../md_docs_2examples.html#autotoc_md65',1,'']]],
  ['interrupt_20pin_20optional_42',['Interrupt Pin (Optional)',['../md_docs_2hardware__setup.html#autotoc_md87',1,'']]],
  ['interrupt_20setup_43',['Basic Interrupt Setup',['../md_docs_2configuration.html#autotoc_md54',1,'']]],
  ['interrupt_20status_44',['Get Interrupt Status',['../md_docs_2configuration.html#autotoc_md56',1,'']]],
  ['interrupts_45',['Interrupts',['../md_docs_2examples.html#autotoc_md66',1,'Configure Multiple Interrupts'],['../md_docs_2api__reference.html#autotoc_md28',1,'Interrupts'],['../md_docs_2troubleshooting.html#autotoc_md149',1,'Q: How do I use interrupts?']]],
  ['invalid_20address_20invalidaddress_46',['Error: Invalid Address (InvalidAddress)',['../md_docs_2troubleshooting.html#autotoc_md145',1,'']]],
  ['invalidaddress_47',['Error: Invalid Address (InvalidAddress)',['../md_docs_2troubleshooting.html#autotoc_md145',1,'']]],
  ['inversion_48',['Polarity Inversion',['../md_docs_2configuration.html#autotoc_md49',1,'']]],
  ['it_49',['2. Create the driver and use it',['../index.html#autotoc_md5',1,'']]]
];
