var searchData=
[
  ['parameter_0',['Parameter',['../md_docs_2platform__integration.html#autotoc_md124',1,'✅ Correct Template Parameter'],['../md_docs_2platform__integration.html#autotoc_md123',1,'❌ Don&apos;t Forget the Template Parameter']]],
  ['pattern_1',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md105',1,'']]],
  ['pca9555_20pcal9555a_2',['Minimal wiring (ESP32-S3 + PCA9555/PCAL9555A)',['../index.html#autotoc_md14',1,'']]],
  ['pca9555_20vs_20pcal9555a_3',['Q: How do I know which chip I have (PCA9555 vs PCAL9555A)?',['../md_docs_2troubleshooting.html#autotoc_md151',1,'']]],
  ['pcal95555_20documentation_4',['HF-PCAL95555 Documentation',['../md_docs_2index.html',1,'']]],
  ['pcal95555_20driver_5',['HF-PCAL95555 Driver',['../index.html',1,'']]],
  ['pcal95555_20i2ctype_20tt_6',['&lt;tt&gt;PCAL95555\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md21',1,'']]],
  ['pcal95555_5fcomprehensive_5ftest_20tt_7',['Comprehensive Test Suite (&lt;tt&gt;pcal95555_comprehensive_test&lt;/tt&gt;)',['../index.html#autotoc_md11',1,'']]],
  ['pcal95555_5fled_5fanimation_20tt_8',['LED Animation Demo (&lt;tt&gt;pcal95555_led_animation&lt;/tt&gt;)',['../index.html#autotoc_md12',1,'']]],
  ['pcal9555a_9',['PCAL9555A',['../index.html#autotoc_md14',1,'Minimal wiring (ESP32-S3 + PCA9555/PCAL9555A)'],['../md_docs_2troubleshooting.html#autotoc_md151',1,'Q: How do I know which chip I have (PCA9555 vs PCAL9555A)?']]],
  ['pcal9555a_20only_10',['PCAL9555A only',['../md_docs_2api__reference.html#autotoc_md27',1,'Drive Strength (PCAL9555A only)'],['../md_docs_2configuration.html#autotoc_md47',1,'Drive Strength (PCAL9555A only)'],['../md_docs_2examples.html#autotoc_md68',1,'Example 5: Drive Strength (PCAL9555A only)'],['../md_docs_2api__reference.html#autotoc_md31',1,'Input Latch (PCAL9555A only)'],['../md_docs_2api__reference.html#autotoc_md29',1,'Output Mode (PCAL9555A only)'],['../md_docs_2configuration.html#autotoc_md48',1,'Output Mode (PCAL9555A only)'],['../md_docs_2configuration.html#autotoc_md46',1,'Pull Resistors (PCAL9555A only)'],['../md_docs_2api__reference.html#autotoc_md26',1,'Pull-up/Pull-down (PCAL9555A only)']]],
  ['per_20pin_20interrupt_20callbacks_11',['Per-Pin Interrupt Callbacks',['../md_docs_2configuration.html#autotoc_md55',1,'']]],
  ['performance_20comparison_12',['Performance Comparison',['../md_docs_2platform__integration.html#autotoc_md112',1,'']]],
  ['physical_20layout_20recommendations_13',['Physical Layout Recommendations',['../md_docs_2hardware__setup.html#autotoc_md83',1,'']]],
  ['pin_20configuration_20table_14',['Address Pin Configuration Table',['../md_docs_2configuration.html#autotoc_md39',1,'']]],
  ['pin_20connections_15',['Pin Connections',['../md_docs_2hardware__setup.html#autotoc_md75',1,'']]],
  ['pin_20descriptions_16',['Pin Descriptions',['../md_docs_2hardware__setup.html#autotoc_md77',1,'']]],
  ['pin_20direction_17',['Pin Direction',['../md_docs_2api__reference.html#autotoc_md24',1,'Pin Direction'],['../md_docs_2configuration.html#autotoc_md45',1,'Pin Direction']]],
  ['pin_20i_20o_18',['Pin I/O',['../md_docs_2api__reference.html#autotoc_md25',1,'']]],
  ['pin_20interrupt_20callbacks_19',['Per-Pin Interrupt Callbacks',['../md_docs_2configuration.html#autotoc_md55',1,'']]],
  ['pin_20optional_20',['Pin Optional',['../md_docs_2hardware__setup.html#autotoc_md87',1,'Interrupt Pin (Optional)'],['../md_docs_2hardware__setup.html#autotoc_md88',1,'Reset Pin (Optional)']]],
  ['pin_20states_21',['Incorrect Pin States',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['pin_20writes_20not_20work_22',['Q: Why do my pin writes not work?',['../md_docs_2troubleshooting.html#autotoc_md148',1,'']]],
  ['pins_23',['Pins',['../md_docs_2configuration.html#autotoc_md58',1,'For Input Pins'],['../md_docs_2configuration.html#autotoc_md59',1,'For Output Pins'],['../md_docs_2hardware__setup.html#autotoc_md78',1,'GPIO Pins'],['../md_docs_2quickstart.html#autotoc_md135',1,'Step 5: Configure and Use Pins']]],
  ['pitfalls_24',['Common Pitfalls',['../md_docs_2platform__integration.html#autotoc_md120',1,'']]],
  ['platform_25',['1. Implement the I2C interface for your platform',['../index.html#autotoc_md4',1,'']]],
  ['platform_20integration_20guide_26',['Platform Integration Guide',['../md_docs_2platform__integration.html',1,'']]],
  ['platform_20specific_20examples_27',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md116',1,'']]],
  ['platforms_28',['Other Platforms',['../md_docs_2examples.html#autotoc_md72',1,'']]],
  ['polarity_29',['Polarity',['../md_docs_2api__reference.html#autotoc_md30',1,'']]],
  ['polarity_20inversion_30',['Polarity Inversion',['../md_docs_2configuration.html#autotoc_md49',1,'']]],
  ['polymorphism_20strong_31',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['power_20requirements_32',['Power Requirements',['../md_docs_2hardware__setup.html#autotoc_md79',1,'']]],
  ['prerequisites_33',['Prerequisites',['../index.html#autotoc_md7',1,'Prerequisites'],['../md_docs_2installation.html#autotoc_md98',1,'Prerequisites'],['../md_docs_2quickstart.html#autotoc_md128',1,'Prerequisites']]],
  ['pull_20resistors_20pcal9555a_20only_34',['Pull Resistors (PCAL9555A only)',['../md_docs_2configuration.html#autotoc_md46',1,'']]],
  ['pull_20up_20and_20pull_20down_35',['Q: What&apos;s the difference between pull-up and pull-down?',['../md_docs_2troubleshooting.html#autotoc_md152',1,'']]],
  ['pull_20up_20pull_20down_20pcal9555a_20only_36',['Pull-up/Pull-down (PCAL9555A only)',['../md_docs_2api__reference.html#autotoc_md26',1,'']]]
];
