var searchData=
[
  ['can_20i_20use_20multiple_20pcal9555a_20devices_0',['Q: Can I use multiple PCAL9555A devices?',['../md_docs_2troubleshooting.html#autotoc_md128',1,'']]],
  ['class_1',['Class',['../md_docs_2api__reference.html#autotoc_md13',1,'Core Class'],['../md_docs_2platform__integration.html#autotoc_md95',1,'Step 1: Create Your Implementation Class']]],
  ['code_2',['Source Code',['../md_docs_2api__reference.html#autotoc_md12',1,'']]],
  ['common_20error_20messages_3',['Common Error Messages',['../md_docs_2troubleshooting.html#autotoc_md120',1,'']]],
  ['common_20pitfalls_4',['Common Pitfalls',['../md_docs_2platform__integration.html#autotoc_md100',1,'']]],
  ['communication_20failures_5',['Error: I2C Communication Failures',['../md_docs_2troubleshooting.html#autotoc_md122',1,'']]],
  ['comparison_6',['Performance Comparison',['../md_docs_2platform__integration.html#autotoc_md92',1,'']]],
  ['compile_20time_20polymorphism_20strong_7',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md88',1,'']]],
  ['configuration_8',['Configuration',['../md_docs_2hardware__setup.html#autotoc_md61',1,'Address Configuration'],['../md_docs_2configuration.html',1,'Configuration'],['../md_docs_2configuration.html#autotoc_md39',1,'Default Configuration'],['../md_docs_2configuration.html#autotoc_md29',1,'I2C Address Configuration'],['../md_docs_2hardware__setup.html#autotoc_md62',1,'I2C Bus Configuration'],['../md_docs_2hardware__setup.html#autotoc_md60',1,'I2C Configuration'],['../md_docs_2configuration.html#autotoc_md41',1,'Interrupt Configuration'],['../md_docs_2configuration.html#autotoc_md33',1,'Runtime Configuration']]],
  ['configuration_20optional_9',['Kconfig Configuration (Optional)',['../md_docs_2configuration.html#autotoc_md30',1,'']]],
  ['configuration_20options_10',['Configuration Options',['../md_docs_2configuration.html#autotoc_md31',1,'']]],
  ['configure_20and_20use_20pins_11',['Step 5: Configure and Use Pins',['../md_docs_2quickstart.html#autotoc_md115',1,'']]],
  ['connections_12',['Connections',['../md_docs_2hardware__setup.html#autotoc_md56',1,'Basic I2C Connections'],['../md_docs_2hardware__setup.html#autotoc_md55',1,'Pin Connections']]],
  ['contents_13',['📚 Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['contributing_14',['🤝 Contributing',['../index.html#autotoc_md9',1,'']]],
  ['control_15',['Example 1: Basic GPIO Control',['../md_docs_2examples.html#autotoc_md50',1,'']]],
  ['copy_20files_16',['Option 1: Copy Files',['../md_docs_2installation.html#autotoc_md80',1,'']]],
  ['core_20class_17',['Core Class',['../md_docs_2api__reference.html#autotoc_md13',1,'']]],
  ['correct_20crtp_20implementation_18',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md102',1,'']]],
  ['correct_20template_20parameter_19',['✅ Correct Template Parameter',['../md_docs_2platform__integration.html#autotoc_md104',1,'']]],
  ['create_20driver_20instance_20',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md113',1,'']]],
  ['create_20your_20implementation_20class_21',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md95',1,'']]],
  ['crtp_20curiously_20recurring_20template_20pattern_22',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md85',1,'']]],
  ['crtp_20implementation_23',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md102',1,'']]],
  ['crtp_20instead_20of_20virtual_20functions_24',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md86',1,'']]],
  ['crtp_20works_25',['How CRTP Works',['../md_docs_2platform__integration.html#autotoc_md91',1,'']]],
  ['curiously_20recurring_20template_20pattern_26',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md85',1,'']]]
];
